# Generated by Django 4.2.3 on 2024-04-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('In Progress', 'In Progress')], default='Pending', max_length=20),
        ),
    ]
