# Generated by Django 4.2.3 on 2024-03-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
