# Generated by Django 4.2.3 on 2024-03-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealerapp', '0002_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrive',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
