# Generated by Django 4.2.3 on 2024-03-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealerapp', '0002_alter_loanapplication_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financier',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
    ]
