# Generated by Django 4.2.3 on 2024-03-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardealerapp', '0003_alter_financier_contact_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
