# Generated by Django 4.2.3 on 2024-03-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealerapp', '0003_testdrive_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
