# Generated by Django 4.2.3 on 2024-03-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealerapp', '0008_alter_car_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('hyundai', 'Hyundai'), ('honda', 'Honda'), ('mahindra', 'Mahindra'), ('ford', 'Ford'), ('kia', 'Kia')], default='', max_length=100),
        ),
    ]
