# Generated by Django 4.2.3 on 2024-03-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealerapp', '0009_alter_car_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('SUV', 'SUV'), ('hatchback', 'Hatchback')], default='', max_length=100),
        ),
    ]
