# Generated by Django 4.2.3 on 2024-03-29 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardealerapp', '0011_alter_car_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financier',
            name='description',
        ),
    ]
