# Generated by Django 4.2.3 on 2024-01-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customUser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customUser',
            table='customUser',
        ),
    ]
