# Generated by Django 4.2.3 on 2024-01-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_auth', '0002_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_date', models.DateTimeField()),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='customUser',
        ),
    ]
