# Generated by Django 4.2.3 on 2024-01-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_auth', '0003_testdrive_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
