# Generated by Django 4.2.3 on 2024-01-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_auth', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestDrive',
        ),
    ]
